name: sequin

services:
  sequin:
    image: sequin/sequin:latest
    pull_policy: always
    ports:
      - "7376:7376"
    networks:
      - sequin-net
    environment:
      - PG_PORT=${PG_PORT}
      - PG_HOSTNAME=${PG_HOSTNAME}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_POOL_SIZE=2
      - ERL_AFLAGS="-proto_dist inet6_tcp"
      - PG_SSL=true
      - SECRET_KEY_BASE=wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If
      - VAULT_KEY=2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=
      - REDIS_URL=redis://sequin_redis:6379
    depends_on:
      sequin_redis:
        condition: service_healthy

  sequin_redis:
    image: redis:7
    ports:
      - "7378:6379"
    networks:
      - sequin-net
    command: ["redis-server", "--port", "6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - sequin_redis_data:/data

  sequin_prometheus:
    image: prom/prometheus
    networks:
      - sequin-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  sequin_grafana:
    image: grafana/grafana
    networks:
      - sequin-net
    ports:
      - "8276:3000"
    depends_on:
      - sequin_prometheus
    volumes:
      - sequin_grafana_data:/var/lib/grafana
      - ./grafana_datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana_dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./dashboard.json:/etc/grafana/dashboards/dashboards/sequin.json

# THIS SECTION WAS MISSING
networks:
  sequin-net:
    driver: bridge

volumes:
  sequin_redis_data:
  sequin_grafana_data: